export const TEST_HEADER_RENAMES: Record<string, string> = {
  TEST_MEDDRA_KOR_NM: "TEST_MEDDRA_KOR",
  TEST_MEDDRA_ENG_NM: "TEST_MEDDRA_ENG",
  TEST_RESULT_CODE: "TEST_RESULT",
  TEST_RESULT_CONT: "TEST_RESULT_CONTENT",
};
