export const DRUG_HEADER_RENAMES: Record<string, string> = {
  DRUG_GB: "DRUG_GROUP",
  DRUG_CD: "DRUG_CODE",
  ACCMLT_DOSAGE_QTY: "ACCUMULATE_DOSAGE_SINCE_ONSET",
  ACCMLT_DOSAGE_QTY_UNIT: "ACCUMULATE_DOSAGE_SINCE_ONSET_UNIT",
  DRUG_ACTION: "DRUG_ACTION_TAKEN",
};
