export const DRUG2_HEADER_RENAMES: Record<string, string> = {
  DOSAGE_INTRVL: "DOSAGE_INTERVAL",
  DOSAGE_INTRVL_UNIT: "DOSAGE_INTERVAL_UNIT",
  DOSAGE_START_DT: "DOSAGE_START_DATE",
  DOSAGE_END_DT: "DOSAGE_END_DATE",
  DOSAGE_TERM: "DOSAGE_ADMINISTRATION PERIOD",
  DOSAGE_TERM_UNIT: "DOSAGE_ADMINISTRATION PERIOD_UNIT",
  BNDE_LOT_NO: "BATCH_LOT_NO",
  DRUG_SHAPE_ID: "DRUG_FORMULATION_ENG",
  DRUG_SHAPE_TXT: "DRUG_FORMULATION_TEXT",
  DOSAGE_ROUTE_ID: "DOSAGE_ROUTE_ENG",
  DOSAGE_ROUTE_TXT: "DOSAGE_ROUTE_TXT",
};
