export const DRUG3_HEADER_RENAMES: Record<string, string> = {
  EFFICACY_MEDDRA_KOR_NM: "INDICATION_MEDDRA_KOR",
  EFFICACY_MEDDRA_ENG_NM: "INDICATION_MEDDRA_ENG",
  DSAS_CD: "PURPOSE OF ADMINISTRATION",
  DSAS_CD_VER: "KCD VERSION",
};
